export type OvertimePayLocale = "ko" | "en";
export const overtimePayContent = {
  ko: {
    title: "연장근로수당 계산기",
    metaTitle: "연장근로수당 계산기 | 시간외수당 계산",
    description:
      "통상시급과 연장근로시간, 가산율로 예상 연장근로수당을 계산합니다.",
    category: "근로·급여 계산기",
    intro: "기본 임금과 가산 임금을 분리해 시간외근로 보상을 확인하세요.",
    input: "연장근로 조건",
    hourlyWage: "통상시급",
    wagePlaceholder: "예: 12,000",
    hours: "급여 정산기간의 총 연장근로시간",
    hoursPlaceholder: "예: 10",
    premium: "가산율",
    premiumPlaceholder: "예: 50",
    workplaceSize: "사업장 규모",
    fiveOrMore: "상시 5인 이상",
    underFive: "상시 5인 미만",
    underFiveNotice:
      "상시 5인 미만 사업장은 근로기준법 제56조 가산임금 규정이 원칙적으로 적용되지 않을 수 있습니다. 입력한 가산율은 근로계약·취업규칙상 약정 가산율일 수 있습니다.",
    calculate: "연장근로수당 계산하기",
    reset: "초기화",
    error: "입력값을 확인해 주세요.",
    result: "예상 결과",
    total: "총 연장근로수당",
    base: "기본 임금분",
    extra: "가산 임금분",
    note: "세전 추정치이며 근로계약과 사업장 적용 기준을 확인해야 합니다.",
    details: "계산 상세",
    effective: "가산 적용 시급",
    appliedHours: "적용 시간",
    appliedRate: "적용 가산율",
    empty: "계산하면 적용한 시간과 가산율이 표시됩니다.",
    explanationTitle: "계산 방법",
    explanation: [
      "기본 임금분은 통상시급 × 연장근로시간입니다.",
      "가산 임금분은 기본 임금분 × 가산율입니다.",
      "총 수당은 기본 임금분과 가산 임금분의 합계입니다.",
    ],
    cautionsTitle: "중요한 주의사항",
    cautions: [
      "상시 5인 이상 사업장은 근로기준법 제56조에 따라 연장근로 가산율을 50% 이상으로 입력해야 합니다. 5인 미만은 계약·취업규칙상 약정 가산율을 입력할 수 있습니다.",
      "주 12시간 한도와 이 입력값은 다른 개념입니다. 입력값은 급여 정산기간 전체의 합계이며, 168시간 상한은 잘못된 대량 입력을 막는 안전 제한일 뿐 법정 허용 한도가 아닙니다.",
      "야간·휴일근로가 겹치면 별도 가산이 추가될 수 있으며 이 계산기는 연장근로 가산만 계산합니다.",
      "통상시급 산정과 실제 근로시간은 급여명세서·근로계약·공식 안내를 확인하세요.",
    ],
    faq: [
      [
        "가산율 50%는 어떻게 계산하나요?",
        "시급의 1.5배를 연장근로시간에 곱한 금액과 같습니다.",
      ],
      [
        "5인 미만 사업장도 같은가요?",
        "근로기준법의 가산임금 규정 적용 여부가 다를 수 있어 사업장 규모와 계약을 확인해야 합니다.",
      ],
      [
        "야간근로도 포함되나요?",
        "아닙니다. 이 계산기는 연장근로 가산만 반영합니다.",
      ],
      ["세후 금액인가요?", "아닙니다. 공제 전 예상 수당입니다."],
    ],
    reference: "국가법령정보센터 근로기준법 제56조",
  },
  en: {
    title: "Korean Overtime Pay Calculator",
    metaTitle: "Korean Overtime Pay Calculator",
    description:
      "Estimate Korean overtime pay from ordinary hourly wage, overtime hours, and a premium rate.",
    category: "Employment calculator",
    intro:
      "Separate ordinary wages and the overtime premium for a clear estimate.",
    input: "Overtime inputs",
    hourlyWage: "Ordinary hourly wage",
    wagePlaceholder: "e.g. 12,000",
    hours: "Total overtime hours in the payroll period",
    hoursPlaceholder: "e.g. 10",
    premium: "Premium rate",
    premiumPlaceholder: "e.g. 50",
    workplaceSize: "Workplace size",
    fiveOrMore: "Five or more regular employees",
    underFive: "Fewer than five regular employees",
    underFiveNotice:
      "Article 56 overtime-premium rules of the Korean Labor Standards Act may generally not apply to workplaces with fewer than five employees. Any entered premium may be contractual or set by workplace rules.",
    calculate: "Calculate overtime pay",
    reset: "Reset",
    error: "Check the highlighted values.",
    result: "Estimated result",
    total: "Total overtime pay",
    base: "Base wage portion",
    extra: "Premium portion",
    note: "A gross estimate; confirm the rules applicable to your workplace and contract.",
    details: "Calculation details",
    effective: "Premium-adjusted hourly pay",
    appliedHours: "Applied hours",
    appliedRate: "Applied premium",
    empty: "Calculate to see the applied hours and premium.",
    explanationTitle: "How it is calculated",
    explanation: [
      "Base pay is ordinary hourly wage multiplied by overtime hours.",
      "Premium pay is base pay multiplied by the premium rate.",
      "Total overtime pay is base pay plus premium pay.",
    ],
    cautionsTitle: "Important cautions",
    cautions: [
      "For workplaces with five or more regular employees, Article 56 requires an overtime premium of at least 50%. Workplaces with fewer than five employees may enter a contractual or workplace-rule premium.",
      "The weekly 12-hour limit is distinct from this input. This input is the total for the payroll period; the 168-hour cap is only a safety limit against unusually large input, not a legal maximum.",
      "Night or holiday work may add separate premiums; this calculator models overtime only.",
      "Confirm ordinary wage and recorded hours with payroll documents and official guidance.",
    ],
    faq: [
      [
        "How does a 50% premium work?",
        "It is equivalent to 1.5 times hourly wage for each overtime hour.",
      ],
      [
        "Does the same rule apply below five employees?",
        "Coverage may differ; check workplace size and your contract.",
      ],
      [
        "Does this include night work?",
        "No. It models the overtime premium only.",
      ],
      ["Is this after tax?", "No. It is a gross estimate before deductions."],
    ],
    reference: "Korean Labor Standards Act, Article 56",
  },
} as const;
