export type Locale = "ko" | "en";
export const content = {
  ko: {
    title: "야간근로수당 계산기",
    metaTitle: "야간근로수당 계산기 | 야간수당 계산",
    description:
      "통상시급과 오후 10시부터 오전 6시 사이의 근로시간으로 예상 야간근로수당을 계산합니다.",
    category: "근로·급여 계산기",
    intro: "야간근로의 기본 임금과 가산 임금을 구분해 확인하세요.",
    input: "야간근로 조건",
    wage: "통상시급",
    wagePh: "예: 12,000",
    hours: "야간근로시간",
    hoursPh: "예: 8",
    rate: "가산율",
    ratePh: "예: 50",
    calculate: "야간근로수당 계산하기",
    reset: "초기화",
    error: "입력값을 확인해 주세요.",
    result: "예상 결과",
    total: "총 야간근로수당",
    base: "기본 임금분",
    premium: "가산 임금분",
    note: "세전 추정치이며 사업장 규모와 중복 가산 여부를 확인하세요.",
    details: "계산 상세",
    adjusted: "가산 적용 시급",
    appliedHours: "적용 시간",
    appliedRate: "적용 가산율",
    empty: "계산하면 적용 조건이 표시됩니다.",
    exTitle: "계산 방법",
    ex: [
      "기본 임금분은 통상시급 × 야간근로시간입니다.",
      "가산 임금분은 기본 임금분 × 가산율입니다.",
      "근로기준법상 야간근로는 오후 10시부터 다음 날 오전 6시 사이의 근로입니다.",
    ],
    warnTitle: "중요한 주의사항",
    warn: [
      "통상적으로 5인 이상 사업장은 야간근로에 50% 이상을 가산하지만 예외가 있을 수 있습니다.",
      "연장·휴일근로와 겹치면 가산 방식이 달라질 수 있으며 이 계산기는 야간 가산만 계산합니다.",
      "실제 지급액은 근로계약과 급여기록을 확인하세요.",
    ],
    faq: [
      [
        "야간근로 시간대는 언제인가요?",
        "오후 10시부터 다음 날 오전 6시까지입니다.",
      ],
      [
        "5인 미만 사업장도 적용되나요?",
        "가산임금 규정 적용 여부가 다를 수 있습니다.",
      ],
      ["연장근로 가산도 포함되나요?", "아닙니다. 야간근로 가산만 계산합니다."],
      ["세후 금액인가요?", "아닙니다. 공제 전 예상액입니다."],
    ],
    reference: "국가법령정보센터 근로기준법 제56조",
  },
  en: {
    title: "Korean Night Work Pay Calculator",
    metaTitle: "Korean Night Work Pay Calculator",
    description:
      "Estimate Korean night-work pay for hours worked between 10 p.m. and 6 a.m.",
    category: "Employment calculator",
    intro: "Separate ordinary wages and the night-work premium.",
    input: "Night-work inputs",
    wage: "Ordinary hourly wage",
    wagePh: "e.g. 12,000",
    hours: "Night-work hours",
    hoursPh: "e.g. 8",
    rate: "Premium rate",
    ratePh: "e.g. 50",
    calculate: "Calculate night-work pay",
    reset: "Reset",
    error: "Check the highlighted values.",
    result: "Estimated result",
    total: "Total night-work pay",
    base: "Base wage portion",
    premium: "Premium portion",
    note: "A gross estimate; confirm workplace coverage and overlapping premiums.",
    details: "Calculation details",
    adjusted: "Premium-adjusted hourly pay",
    appliedHours: "Applied hours",
    appliedRate: "Applied premium",
    empty: "Calculate to see the applied conditions.",
    exTitle: "How it is calculated",
    ex: [
      "Base pay is hourly wage multiplied by night-work hours.",
      "Premium pay is base pay multiplied by the premium rate.",
      "Night work is work between 10 p.m. and 6 a.m. under Korean law.",
    ],
    warnTitle: "Important cautions",
    warn: [
      "A 50% or higher premium generally applies at workplaces with at least five employees, subject to exceptions.",
      "Overtime or holiday overlap can change premiums; this calculator models night work only.",
      "Confirm actual payment with your contract and payroll records.",
    ],
    faq: [
      ["What hours count as night work?", "Hours between 10 p.m. and 6 a.m."],
      ["Does it apply below five employees?", "Coverage may differ."],
      ["Does this include overtime?", "No. It models the night premium only."],
      ["Is this after tax?", "No. It is before deductions."],
    ],
    reference: "Korean Labor Standards Act, Article 56",
  },
} as const;
